[features]
seeds = false
skip-lint = false
[programs.devnet]
dapp = "86w3PTo469NcgUzYK2UEGCMdNZnK36h6iHQ9FFcM3Qcp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shiyas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
